// loaders
export const CONNECTION_ENABLE_LOADER = 'CONNECTION_ENABLE_LOADER';
export const CONNECTION_DISABLE_LOADER = 'CONNECTION_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// CONNECTION
export const CONNECTION_REQUEST = 'CONNECTION_REQUEST';
export const CONNECTION_RESPONSE = 'CONNECTION_RESPONSE';
export const CONNECTION_LOADING_ENDED = 'CONNECTION_LOADING_ENDED';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const DISCONNECT = 'DISCONNECT';
export const DISCONNECT_SUCCESS = 'DISCONNECT_SUCCESS';

export const ORDERBOOK_RESPONSE = 'ORDERBOOK_RESPONSE';
export const ORDERBOOK_RESET = 'ORDERBOOK_RESET';
